apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator  # This matches the label from your deployment
  ports:
    - protocol: TCP
      port: 8081        # Port on which the service will be accessible
      targetPort: 8081  
  type: LoadBalancer  
