name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx (optional but recommended)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub secrets for security
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the base Docker image
      run: docker pull murali54321/python-calculator  # Pull the base image from Docker Hub

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag murali54321/python-calculator:$(date +%s)

    - name: Tag the Docker image as latest
      run: docker tag murali54321/python-calculator:$(date +%s) murali54321/python-calculator:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker push murali54321/python-calculator:$(date +%s)
        docker push murali54321/python-calculator:latest
