name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx (optional but recommended)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets for security
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the base Docker image
      run: docker pull murali54321/python-calculator || true  # Avoid failure if image doesn't exist

    - name: Set timestamp for image versioning
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag murali54321/python-calculator:${{ env.TIMESTAMP }}

    - name: Tag the Docker image as latest
      run: docker tag murali54321/python-calculator:${{ env.TIMESTAMP }} murali54321/python-calculator:latest

    - name: Push the Docker images to Docker Hub
      run: |
        docker push murali54321/python-calculator:${{ env.TIMESTAMP }}
        docker push murali54321/python-calculator:latest
