name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
          branch: gh-pages # Use the branch you want to deploy to GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Upload the entire repository or just the build folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
